### ISSUE TITLE
Allow using keywords as relation, type and condition names

### ISSUE THREAD

**Issue by rhamzeh** [openfga/language#170]
An example test that would need to work:

For now, we'll keep the following as reserved:
```
and
or
from
relations
define
```
as reserved, but allow
```
model
schema
type
relation
condition
```

```yaml
# dsl-syntax-validation-cases.yaml
- name: a valid model with type names doesn't conflict with built-in keywords
  dsl: |
    model
      schema 1.1
    type user
    type model
      relations
        define model: [user]
        define schema: [user]
        define type: [user]
        define relation: [user]
        define condition: [user] or model or schema or type or relation
    type schema
      relations
        define model: [user]
        define schema: [user]
        define type: [user]
        define relation: [user]
        define condition: [user] or model or schema or type or relation
    type type
      relations
        define model: [user]
        define schema: [user]
        define type: [user]
        define relation: [user]
        define condition: [user] or model or schema or type or relation
    type relation
      relations
        define model: [user]
        define schema: [user]
        define type: [user]
        define relation: [user]
        define condition: [user] or model or schema or type or relation
    type condition
      relations
        define model: [user]
        define schema: [user]
        define type: [user]
        define relation: [user]
        define condition: [user] or model or schema or type or relation
```
