### ISSUE TITLE
Validation location errors found in java implementation 

### ISSUE THREAD

**Issue by d-jeffery** [openfga/language#259]
Found some validation errors when using the latest java build from main;

Incorrect highlight of definition name, instead of type reference;
![image](https://github.com/openfga/language/assets/1425457/fe55ff49-a299-4edf-af86-9e7f1e3e3b4d)

All errors being assigned to first occurrence of type reference;
![image](https://github.com/openfga/language/assets/1425457/6e5f0de7-acf6-4016-b158-0fb8de4d3a4b)

**Comment by d-jeffery** [comment]
If given a definition where the relation name and direct relation are the same word - the type is highlighted instead
https://github.com/openfga/language/blob/main/pkg/js/util/exceptions.ts#L433

Test case:
```yaml

- name: invalid type error maps to wrong location when duplicate relation name is used in direct assignment
  dsl: |
    model
      schema 1.1
    type custome
    type bank
      relations
        define customer : [customer]
    type account
      relations
        define owner : [customer]
  expected_errors:
    - msg: "`customer` is not a valid type."
      line:
        start: 5
        end: 5
      column:
        start: 23
        end: 31
      metadata:
        errorType: invalid-type
    - msg: "`customer` is not a valid type."
      line:
        start: 8
        end: 8
      column:
        start: 20
        end: 28
      metadata:
        errorType: invalid-type
```
